### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by DanJ210** [shawnwildermuth/BuildingWebASPNETCore#4]
I'm using your pluralsight course and learning a lot so thank you very much. I couldn't leave a comment on pluralsight as those are closed off for some reason so I'm showing my appreciation here as I'm getting the location data to seed. Again thanks a lot, very good teaching. You are welcome to remove this because I feel like I may upset you somewhat for posting this where it is out of context.

Also, no more project.json!!! They switched to the .csproj file now. That hasn't been an issue so far as I've been adding dependencies via the nuget package manage just fine. Thought I would share that at least as the only issue I've come across but really hasn't been an issue.

**Comment by shawnwildermuth** [comment]
I'm investigating why the comments are closed. We're looking at how to patch the course for csproj. It should be complete in the next month or so.
