### ISSUE TITLE
Some criticism 

### ISSUE THREAD

**Issue by Wholteza** [shawnwildermuth/BuildingWebASPNETCore#5]
I'm following your courses on Pluralsight and i find them really good and perfectly in depth with what you need to know to use various tools. 

I only have one suggestion if you were (and i hope) to make more courses, and that is to not change file-, directory-, property- or class-names off camera. I sometimes notice from clip to clip that you have changed something minor that breaks the build for me as a follower, things like renaming "Stops" to "Stop" when we've already built the database once. Or moving a controller in the structure.

I don't have a problem fixing these issues on my own but i can see a lot of newbies that will pull their hair out, not understanding what's wrong.

So if you have to do these kinds of changes, include them visually in the next clip to make it easy for the viewer.

No offence, just wanting to make your content even better. 
Sincerely, Zackarias Montell.

**Comment by shawnwildermuth** [comment]
Becuase the course was made with lots and lots of re-shoots (over the Beta 6, 7,,8, RC, RTM, etc.), some of these edits got rough. That's why for v2, I reshot the entire course from scratch.
